# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(choices=[('Ford', 'Ford'), ('Hyundai', 'Hyundai'), ('Chevrolet', 'Chevrolet'), ('Citroen', 'Citroen'), ('VW', 'VW'), ('Renault', 'Renault'), ('Peugeot', 'Peugeot'), ('Opel', 'Opel')], max_length=255)),
                ('model', models.CharField(choices=[('Fusion', 'Fusion'), ('Solaris', 'Solaris'), ('Lacetti', 'Lacetti'), ('C4', 'C4'), ('Aveo', 'Aveo'), ('Polo', 'Polo'), ('Symbol', 'Symbol'), ('308', '308'), ('Cobalt', 'Cobalt'), ('Astra', 'Astra')], max_length=255)),
                ('body_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('Wagon', 'Wagon')], max_length=255)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('number_of_owners', models.PositiveSmallIntegerField()),
                ('announced_price', models.PositiveIntegerField()),
                ('negotiated_price', models.PositiveIntegerField(null=True)),
                ('phone_number', models.CharField(max_length=255, verbose_name='79200393289')),
                ('link', models.CharField(max_length=1024)),
            ],
        ),
    ]
