# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170413_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Red', 'Red'), ('Dark grey', 'Dark grey'), ('Blue', 'Blue'), ('Silver', 'Silver'), ('Silver-blue', 'Silver-blue'), ('Silver-beige', 'Silver-beige'), ('Black', 'Black')], max_length=255, null=True),
        ),
    ]
