# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170413_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
